language: go

go:
- "1.10"

env:
- DEP_VERSION="0.4.1"

branches:
  only:
    - atlas-patch

install:
# Download and install dep
- mv $GOPATH/src/github.com/infobloxopen $GOPATH/src/github.com/grpc-ecosystem
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- dep ensure -vendor-only

script:
- go install ./protoc-gen-swagger

# Trigger build/push of latest gentool
deploy:
  on:
    branch: atlas-patch
  provider: script
  script:  curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh && sh trigger-travis.sh infobloxopen atlas-gentool $TRAVIS_ACCESS_TOKEN